const primaryLight  = '#18181B';
const primaryDark   = '#E4E4E7';
const successLight  = '#22C55E';
const dangerLight   = '#EF4444';
const warningLight  = '#F59E0B';
// Dark semantics are generated from the light ones (W2-20) — lighter and less saturated — the
// same way a preset's dark half is. The Tailwind-400 shades the app used to reuse at full strength
// read as neon against a dark ground. (`toDarkVariant` is a function declaration, so it hoists.)
const successDark   = toDarkVariant(successLight);
const dangerDark    = toDarkVariant(dangerLight);
const warningDark   = toDarkVariant(warningLight);

/**
 * The palette as it is written down: surfaces, accents and semantic colours only.
 * Foregrounds are deliberately absent — see `ThemeColors` below.
 *
 * Surfaces are three tones, not shadows (W2-20/W2-22): `background` is the page, `card` sits on
 * it, `cardAlt` sits on a card (chips, badges, the pressed state). In dark they step *up* in
 * lightness so elevation stays legible where a shadow is invisible; in light they step down and
 * a hairline border does the rest. `surface`, `inputBg` and `separator` are aliases onto those
 * three so nothing has a fourth tone to drift to.
 */
export type BaseColors = {
  text: string;
  secondaryText: string;
  background: string;
  card: string;
  cardAlt: string;
  border: string;
  separator: string;
  surface: string;
  inputBg: string;
  tint: string;
  icon: string;
  tabIconDefault: string;
  tabIconSelected: string;
  income: string;
  expense: string;
  primary: string;
  success: string;
  danger: string;
  warning: string;
  chart: string[];
};

/**
 * A palette with its foregrounds derived. Every `*Text` token is computed from the colour it sits
 * on, never written by hand — that is the whole point (W2-01/W2-02). Build one with
 * `withContrastText`, or take the live one from `useTheme()`, which also folds in presets and
 * user overrides. A preset may declare its own foreground; nothing else may.
 */
export type ThemeColors = BaseColors & {
  tintText: string;
  incomeText: string;
  expenseText: string;
  warningText: string;
};

export const Colors: { light: BaseColors; dark: BaseColors } = {
  light: {
    text:            '#18181B',
    secondaryText:   '#636369',
    background:      '#F5F5F5',
    card:            '#FFFFFF',
    cardAlt:         '#E5E7EB',
    border:          '#D1D5DB',
    separator:       '#E5E7EB',
    surface:         '#F3F4F6',
    inputBg:         '#FFFFFF',
    tint:            primaryLight,
    icon:            '#71717A',
    tabIconDefault:  '#85858E',
    tabIconSelected: primaryLight,
    income:          successLight,
    expense:         dangerLight,
    primary:         primaryLight,
    success:         successLight,
    danger:          dangerLight,
    warning:         warningLight,
    chart: ['#18181B','#27272A','#3F3F46','#52525B','#71717A','#A1A1AA','#D4D4D8'],
  },
  dark: {
    text:            '#F4F4F5',
    secondaryText:   '#A1A1AA',
    // Off near-black (was #09090B): a base that deep leaves the raised tones nowhere to go.
    background:      '#111114',
    card:            '#1C1C21',
    cardAlt:         '#28282E',
    border:          '#383840',
    separator:       '#28282E',
    surface:         '#1C1C21',
    inputBg:         '#1C1C21',
    tint:            primaryDark,
    icon:            '#A1A1AA',
    tabIconDefault:  '#71717A',
    tabIconSelected: primaryDark,
    income:          successDark,
    expense:         dangerDark,
    primary:         primaryDark,
    success:         successDark,
    danger:          dangerDark,
    warning:         warningDark,
    chart: ['#F4F4F5','#E7E5E4','#D4D4D8','#A1A1AA','#71717A','#52525B','#3F3F46'],
  },
};

// A preset states the three surface colours and nothing else. It used to declare its own
// foregrounds too, and 25 of those 48 pairs were below 4.5:1, so ThemeContext computes them
// all from the surface now and there is nothing here for a new preset to get wrong.
//
// Since W2-20 a preset is *seeded* with its light colours only; the dark scheme is generated by
// `toDarkVariant` (lighter, less saturated), so a new preset cannot ship a dark half that vibrates
// or fails contrast — `tests/contrast.test.mjs` walks the generated result.
export interface PresetColors {
  accent: string;
  income: string;
  expense: string;
}

export interface ThemePreset {
  name: string;
  light: PresetColors;
  dark: PresetColors;
}

interface PresetSeed { name: string; accent: string; income: string; expense: string }

const PRESET_SEEDS: PresetSeed[] = [
  { name: 'Graphite', accent: '#18181B', income: successLight, expense: dangerLight },
  { name: 'Ocean',    accent: '#2563EB', income: '#10B981',    expense: '#F43F5E' },
  { name: 'Forest',   accent: '#16A34A', income: '#059669',    expense: '#DC2626' },
  { name: 'Dusk',     accent: '#7C3AED', income: '#0EA5E9',    expense: '#EC4899' },
  { name: 'Ember',    accent: '#EA580C', income: '#16A34A',    expense: '#DC2626' },
  { name: 'Pearl',    accent: '#475569', income: '#0EA5E9',    expense: '#F43F5E' },
  { name: 'Azure',    accent: '#0369A1', income: '#10B981',    expense: '#F43F5E' },
  { name: 'Coral',    accent: '#E11D48', income: '#0EA5E9',    expense: '#E11D48' },
];

function hexToHsl(hex: string): [number, number, number] {
  const c = hex.replace('#', '');
  const r = parseInt(c.substring(0, 2), 16) / 255;
  const g = parseInt(c.substring(2, 4), 16) / 255;
  const b = parseInt(c.substring(4, 6), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min;
  const sat = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h = 0;
  if (max === r)      h = (g - b) / d + (g < b ? 6 : 0);
  else if (max === g) h = (b - r) / d + 2;
  else                h = (r - g) / d + 4;
  return [h * 60, sat, l];
}

function hslToHex(h: number, sat: number, l: number): string {
  const k = (n: number) => (n + h / 30) % 12;
  const a = sat * Math.min(l, 1 - l);
  const f = (n: number) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  const to = (x: number) => Math.round(x * 255).toString(16).padStart(2, '0').toUpperCase();
  return `#${to(f(0))}${to(f(8))}${to(f(4))}`;
}

/**
 * The dark-scheme twin of a light colour: lighter, so it reads on a dark ground, and at ~80% of
 * its saturation, so it does not glow. A neutral (a grey accent like Graphite's) goes near-white
 * instead — the point of a neutral accent is that it is the brightest thing on the screen.
 */
export function toDarkVariant(hex: string): string {
  const [h, sat, l] = hexToHsl(hex);
  if (sat < 0.15) return hslToHex(h, sat, 0.9);
  return hslToHex(h, sat * 0.8, Math.max(l, 0.68));
}

export const THEME_PRESETS: ThemePreset[] = PRESET_SEEDS.map(seed => ({
  name:  seed.name,
  light: { accent: seed.accent, income: seed.income, expense: seed.expense },
  dark:  {
    accent:  seed.name === 'Graphite' ? primaryDark : toDarkVariant(seed.accent),
    income:  toDarkVariant(seed.income),
    expense: toDarkVariant(seed.expense),
  },
}));


let _currencySymbol = '₹';
let _currencyLocale = 'en-IN';

export function applyCurrency(symbol: string, locale: string): void {
  _currencySymbol = symbol;
  _currencyLocale = locale;
}

export const Currency = {
  get symbol() { return _currencySymbol; },
  format: (amount: number) =>
    `${_currencySymbol} ${(amount || 0).toLocaleString(_currencyLocale, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`,
};

export const TYPE_SCALE = {
  heroAmount:   { fontSize: 48, fontWeight: '800' as const, fontVariant: ['tabular-nums'] as const, letterSpacing: -0.5 },
  screenTitle:  { fontSize: 24, fontWeight: '800' as const },
  sectionTitle: { fontSize: 17, fontWeight: '700' as const },
  body:         { fontSize: 15, fontWeight: '500' as const },
  label:        { fontSize: 13, fontWeight: '600' as const },
  caption:      { fontSize: 11, fontWeight: '500' as const },
};

export const CATEGORIES = [
  { id: '1', name: 'Food',          icon: 'fast-food' },
  { id: '2', name: 'Transport',     icon: 'car' },
  { id: '3', name: 'Shopping',      icon: 'cart' },
  { id: '4', name: 'Rent',          icon: 'home' },
  { id: '5', name: 'Entertainment', icon: 'game-controller' },
  { id: '6', name: 'Other',         icon: 'ellipsis-horizontal' },
];

export const CATEGORY_COLORS = {
  'Food':          { bg: '#F3F4F6', icon: '#18181B' },
  'Transport':     { bg: '#E5E7EB', icon: '#27272A' },
  'Shopping':      { bg: '#F4F4F5', icon: '#3F3F46' },
  'Health':        { bg: '#E7E5E4', icon: '#52525B' },
  'Entertainment': { bg: '#F5F5F4', icon: '#71717A' },
  'Bills':         { bg: '#E5E7EB', icon: '#3F3F46' },
  'Rent':          { bg: '#E5E7EB', icon: '#27272A' },
  'Education':     { bg: '#F3F4F6', icon: '#52525B' },
  'Salary':        { bg: '#E5E7EB', icon: '#18181B' },
  'Business':      { bg: '#F3F4F6', icon: '#3F3F46' },
  'Investment':    { bg: '#F9FAFB', icon: '#71717A' },
  'Other':         { bg: '#F5F5F5', icon: '#9CA3AF' },
};

export const BORDER_RADIUS = {
  card: 16,
  input: 12,
  chip: 8,
  button: 14,
  pill: 999,
  avatar: '50%',
};

export function hexToRGBA(hex: string, alpha: number): string {
  const cleanHex = hex.replace('#', '');
  const r = parseInt(cleanHex.substring(0, 2), 16);
  const g = parseInt(cleanHex.substring(2, 4), 16);
  const b = parseInt(cleanHex.substring(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// The only two foregrounds the app ever puts on a coloured surface.
export const CONTRAST_LIGHT = '#FFFFFF';
export const CONTRAST_DARK  = '#18181B';

// Returns CONTRAST_LIGHT for dark backgrounds, CONTRAST_DARK for light ones (WCAG luminance)
export function getContrastText(hex: string): string {
  const clean = hex.replace('#', '');
  const r = parseInt(clean.substring(0, 2), 16);
  const g = parseInt(clean.substring(2, 4), 16);
  const b = parseInt(clean.substring(4, 6), 16);
  const toLinear = (c: number) => { const s = c / 255; return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4); };
  const lum = 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
  // The familiar 0.179 crossover is the one for white vs *pure black*; the dark token here is
  // #18181B (luminance 0.00927), so the point where the two stop being equally good sits at
  // sqrt((1 + 0.05) * (0.00927 + 0.05)) - 0.05. Using 0.179 handed #6366F1 dark text at 3.97:1
  // when white would have given 4.47:1.
  return lum > 0.1995 ? CONTRAST_DARK : CONTRAST_LIGHT;
}

/**
 * Derive the four foreground tokens for a palette. `ThemeContext` layers presets and overrides on
 * top of this; anything reading `Colors` directly should go through it rather than assuming white.
 */
export function withContrastText(base: BaseColors): ThemeColors {
  return {
    ...base,
    tintText:    getContrastText(base.tint),
    incomeText:  getContrastText(base.income),
    expenseText: getContrastText(base.expense),
    warningText: getContrastText(base.warning),
  };
}

/**
 * The two palettes with their foregrounds derived, for the rare reader that runs outside
 * `ThemeContext` and so cannot see presets or user overrides. Prefer `useTheme()`.
 */
export const StaticThemes: { light: ThemeColors; dark: ThemeColors } = {
  light: withContrastText(Colors.light),
  dark:  withContrastText(Colors.dark),
};

export function getCategoryColors(category: string, isDark: boolean) {
  const base = CATEGORY_COLORS[category as keyof typeof CATEGORY_COLORS] || CATEGORY_COLORS['Other'];
  if (isDark) {
    return {
      bg: hexToRGBA(base.icon, 0.15),
      icon: base.icon,
    };
  }
  return base;
}

